//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneDbEntities : DbContext
    {
        public KutuphaneDbEntities()
            : base("name=KutuphaneDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_EmanetListesi> tbl_EmanetListesi { get; set; }
        public virtual DbSet<tbl_KitapListesi> tbl_KitapListesi { get; set; }
        public virtual DbSet<tbl_OkuyucuListesi> tbl_OkuyucuListesi { get; set; }
        public virtual DbSet<tbl_Uyeler> tbl_Uyeler { get; set; }
        public virtual DbSet<tbl_YayinEvleri> tbl_YayinEvleri { get; set; }
        public virtual DbSet<tbl_Yazarlar> tbl_Yazarlar { get; set; }
    }
}
