//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmanetListesi
    {
        public string Barkod { get; set; }
        public string EmanetTarihi { get; set; }
        public string DonusTarihi { get; set; }
        public int ID { get; set; }
        public Nullable<int> OkuyucuID { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<int> KitapId { get; set; }
    
        public virtual tbl_KitapListesi tbl_KitapListesi { get; set; }
        public virtual tbl_OkuyucuListesi tbl_OkuyucuListesi { get; set; }
    }
}
