//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uyeler
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Sifre { get; set; }
        public string Kadi { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Unvan { get; set; }
    }
}
